# Generated by Django 5.1 on 2024-08-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_generatedtoken_tokenstoremobile_tokenstorepc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtoken',
            name='contact_no',
        ),
    ]
