# Generated by Django 5.1 on 2024-08-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_generatedtoken_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtoken',
            name='verification',
        ),
    ]
