# Generated by Django 5.1 on 2024-10-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_generatedtoken_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstorepc',
            name='key',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
