# Generated by Django 5.1 on 2024-10-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tokenstorepc_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstorepc',
            name='IV',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
