# Generated by Django 5.1 on 2024-12-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tokenstorepc_iv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenstorepc',
            name='IV',
        ),
        migrations.RemoveField(
            model_name='tokenstorepc',
            name='key',
        ),
    ]
